services:
  postgres:
    environment:
      POSTGRES_DB: fso2f
      POSTGRES_PASSWORD: fso2f
      POSTGRES_USER: fso2f
    image: postgres:15
    ports:
      - "5432:5432"
    command: -c fsync=off -c full_page_writes=off
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "fso2f", "-U", "fso2f"]
      interval: 5s
      timeout: 4s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data

  products-subgraph:
    image: rust:1.84
    working_dir: /app
    command: sh -c "rustup default nightly && cargo run --bin products-subgraph"
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://fso2f:fso2f@postgres:5432/fso2f
      RUST_LOG: info
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    depends_on:
      postgres:
        condition: service_healthy

  orders-subgraph:
    image: rust:1.84
    working_dir: /app
    command: sh -c "rustup default nightly && cargo run --bin orders-subgraph"
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: postgres://fso2f:fso2f@postgres:5432/fso2f
      RUST_LOG: info
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    depends_on:
      postgres:
        condition: service_healthy

  wundergraph-router:
    image: ghcr.io/wundergraph/cosmo/router
    environment:
      LOG_LEVEL: info
      CORS_ALLOW_CREDENTIALS: true
      LISTEN_ADDR: '0.0.0.0:5000'
    volumes:
      - ./schemas/federation/router.json:/router.json
      - ./schemas/federation/config.yaml:/config.yaml
    ports:
      - '5000:5000'

volumes:
  postgres: {}
  cargo-cache: {}
  target-cache: {}
