[env]
CC = "/usr/bin/clang"
CXX = "/usr/bin/clang++"
AR = "/usr/bin/ar"
RANLIB = "/usr/bin/ranlib"
SDKROOT = "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"

[target.aarch64-apple-darwin]
linker = "/usr/bin/clang"
