type Customer {
	id: ID!
	name: String!
	vat: String!
}

scalar Money

type Order {
	id: ID!
	customer: Customer!
	totalAmount: Money!
	status: OrderStatus!
	lines: [OrderLine!]!
}

type OrderLine {
	id: ID!
	product: ProductKind!
	quantity: Int!
	price: Money!
	discount: Money
}

enum OrderStatus {
	DRAFT
	CONFIRMED
	Cancelled
}

type ProductKind @key(fields: "id") @interfaceObject {
	id: ID!
}

type Query {
	order(id: ID!): Order
}

"""
Directs the executor to include this field or fragment only when the `if` argument is true.
"""
directive @include(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
"""
Directs the executor to skip this field or fragment when the `if` argument is true.
"""
directive @skip(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
extend schema @link(
	url: "https://specs.apollo.dev/federation/v2.5",
	import: ["@key", "@tag", "@shareable", "@inaccessible", "@override", "@external", "@provides", "@requires", "@composeDirective", "@interfaceObject", "@requiresScopes"]
)
