input CreateDangerousProduct {
	code: String!
	description: String!
	maxTemperature: Float!
}

input CreateExpiringProduct {
	code: String!
	description: String!
	expirationDate: DateTime!
}

input CreateProduct {
	code: String!
	description: String!
}

input CreateProductKind @oneOf {
	product: CreateProduct
	dangerousProduct: CreateDangerousProduct
	expiringProduct: CreateExpiringProduct
}

type DangerousProduct implements ProductKind @key(fields: "id") {
	id: ID!
	code: String!
	description: String!
	maxTemperature: Float!
}

"""
Implement the DateTime<Utc> scalar

The input/output is a string in RFC3339 format.
"""
scalar DateTime

type ExpiringProduct implements ProductKind @key(fields: "id") {
	id: ID!
	code: String!
	description: String!
	expirationDate: DateTime!
}

type Mutation {
	createProduct(product: CreateProductKind!): ProductKind!
}

type Product implements ProductKind @key(fields: "id") {
	id: ID!
	code: String!
	description: String!
}

interface ProductKind @key(fields: "id") {
	id: ID!
	code: String!
	description: String!
}

type Query {
	product(code: String!): ProductKind
}

"""
Directs the executor to include this field or fragment only when the `if` argument is true.
"""
directive @include(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
"""
Indicates that an Input Object is a OneOf Input Object (and thus requires exactly one of its field be provided)
"""
directive @oneOf on INPUT_OBJECT
"""
Directs the executor to skip this field or fragment when the `if` argument is true.
"""
directive @skip(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
"""
Provides a scalar specification URL for specifying the behavior of custom scalar types.
"""
directive @specifiedBy(url: String!) on SCALAR
extend schema @link(
	url: "https://specs.apollo.dev/federation/v2.5",
	import: ["@key", "@tag", "@shareable", "@inaccessible", "@override", "@external", "@provides", "@requires", "@composeDirective", "@interfaceObject", "@requiresScopes"]
)
