input CreateOrder {
	customer: CustomerInput!
	items: [CreateOrderLine!]!
}

input CreateOrderLine {
	productId: ID!
	quantity: Int!
}

type Customer {
	name: String!
	vat: String!
}

input CustomerInput {
	name: String!
	vat: String!
}

type Mutation {
	createOrder(order: CreateOrder!): Order!
}

type Order {
	id: OrderId!
	customer: Customer!
	totalAmount: Float!
	status: OrderStatus!
	lines: [OrderLine!]!
}

scalar OrderId

type OrderLine {
	lineNumber: Int!
	quantity: Int!
	discount: Float
	product: SimpleProduct!
}

enum OrderStatus {
	DRAFT
	CONFIRMED
	Cancelled
}

type Query {
	order(id: OrderId!): Order!
}

type SimpleProduct @key(fields: "id") @shareable {
	id: ID!
	pippo: String!
}

"""
Directs the executor to include this field or fragment only when the `if` argument is true.
"""
directive @include(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
"""
Directs the executor to skip this field or fragment when the `if` argument is true.
"""
directive @skip(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
extend schema @link(
	url: "https://specs.apollo.dev/federation/v2.5",
	import: ["@key", "@tag", "@shareable", "@inaccessible", "@override", "@external", "@provides", "@requires", "@composeDirective", "@interfaceObject", "@requiresScopes"]
)
