type DangerousProduct implements Product @key(fields: "id") {
	id: ID! @shareable
	kind: String! @shareable
	code: String! @shareable
	description: String! @shareable
	maxTemperature: Float!
}

"""
Implement the DateTime<Utc> scalar

The input/output is a string in RFC3339 format.
"""
scalar DateTime

type ExpiringProduct implements Product @key(fields: "id") {
	id: ID! @shareable
	kind: String! @shareable
	code: String! @shareable
	description: String! @shareable
	expirationDate: DateTime!
}

interface Product @key(fields: "id") {
	id: ID!
	kind: String!
	code: String!
	description: String!
}

type Query {
	productById(id: ID!): Product
}

type StandardProduct implements Product @key(fields: "id") {
	id: ID! @shareable
	kind: String! @shareable
	code: String! @shareable
	description: String! @shareable
}

"""
Directs the executor to include this field or fragment only when the `if` argument is true.
"""
directive @include(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
"""
Directs the executor to skip this field or fragment when the `if` argument is true.
"""
directive @skip(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
"""
Provides a scalar specification URL for specifying the behavior of custom scalar types.
"""
directive @specifiedBy(url: String!) on SCALAR
extend schema @link(
	url: "https://specs.apollo.dev/federation/v2.5",
	import: ["@key", "@tag", "@shareable", "@inaccessible", "@override", "@external", "@provides", "@requires", "@composeDirective", "@interfaceObject", "@requiresScopes"]
)
