schema {
  query: Query
  mutation: Mutation
}

"""
Implement the DateTime<Utc> scalar

The input/output is a string in RFC3339 format.
"""
scalar DateTime

interface ProductKind {
  id: ID!
  kind: String!
  code: String!
  description: String!
}

type Query {
  productById(id: ID!): ProductKind
  order(id: OrderId!): Order!
}

input CreateOrder {
  customer: CustomerInput!
  items: [CreateOrderLine!]!
}

input CreateOrderLine {
  productId: ID!
  quantity: Int!
}

type Customer {
  id: ID!
  name: String!
  vat: String!
}

input CustomerInput {
  id: ID!
  name: String!
  vat: String!
}

type Mutation {
  createOrder(order: CreateOrder!): Order!
}

type Order {
  id: OrderId!
  customer: Customer!
  totalAmount: Float!
  status: OrderStatus!
  lines: [OrderLine!]!
}

scalar OrderId

type OrderLine {
  lineNumber: Int!
  quantity: Int!
  product: ProductKind!
}

enum OrderStatus {
  DRAFT
  CONFIRMED
  Cancelled
}

type DangerousProduct implements ProductKind {
  id: ID!
  kind: String!
  code: String!
  description: String!
  maxTemperature: Float!
}

type ExpiringProduct implements ProductKind {
  id: ID!
  kind: String!
  code: String!
  description: String!
  expirationDate: DateTime!
}

type Product implements ProductKind {
  id: ID!
  kind: String!
  code: String!
  description: String!
}
