schema {
  query: Query
  mutation: Mutation
}

type Query {
  product(code: String!): SimpleProduct!
  order(id: OrderId!): Order!
  customer(id: ID!): Customer!
}

type SimpleProduct {
  id: ID!
  code: String!
  description: String!
  pippo: String!
}

input CreateOrder {
  customer: CustomerInput!
  items: [CreateOrderLine!]!
}

input CreateOrderLine {
  productId: ID!
  quantity: Int!
}

type Customer {
  id: ID!
  """This field uses @override to take control from the orders subgraph"""
  name: String!
  vat: String!
  """New fields owned by customers subgraph"""
  email: String!
  phone: String
}

input CustomerInput {
  id: ID!
  name: String!
  vat: String!
}

type Mutation {
  createOrder(order: CreateOrder!): Order!
}

type Order {
  id: OrderId!
  customer: Customer!
  totalAmount: Float!
  status: OrderStatus!
  lines: [OrderLine!]!
}

scalar OrderId

type OrderLine {
  lineNumber: Int!
  quantity: Int!
  discount: Float
  product: SimpleProduct!
}

enum OrderStatus {
  DRAFT
  CONFIRMED
  Cancelled
}
