version: 1
subgraphs:
  - name: subgraph-products
    routing_url: http://products-subgraph:3001/graphql
    schema:
      file: ../09_products.graphql
  - name: subgraph-orders
    routing_url: http://orders-subgraph:3002/graphql
    schema:
      file: ../09_orders.graphql
