version: 1
subgraphs:
  - name: subgraph-products
    routing_url: http://products-subgraph-local:3001/graphql
    schema:
      file: ../10_products.graphql
  - name: subgraph-orders
    routing_url: http://orders-subgraph-local:3002/graphql
    schema:
      file: ../10_orders.graphql
